name: Running a testsuite

on:
  push:
    branches:
      - main

env:
  GKE_CLUSTER_NAME: testkube-workshop
  GKE_ZONE: us-east1-c
  POSTMAN_TEST_FILE_NANE: petstore_postman_collection.json
  POSTMAN_TEST_FILE_PATH: postman

jobs:
  run_testsuite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@94337306dda8180d967a56932ceb4ddcf01edae7
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      # Runnning test suite
      - name: Run test suite
        run: |-
          # enabling debug mode
          set -x

          # Installing testkube kubectl plugin:
          bash < <(curl -sSLf https://kubeshop.github.io/testkube/install.sh )

          # Downloading test suite:
          curl -LOs https://raw.githubusercontent.com/kubeshop/nordictestingdays-2022/main/testsuite/testsuite.json

          # Running Test suite:
          cat testsuite.json | kubectl testkube create testsuite --name workshop-testkube-testsuite

          # Checking if Test suite was created
          kubectl get testsuites -ntestkube


